version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  reviewers:
  - anthonymonori
  ignore:
  - dependency-name: com.android.tools.build:gradle
    versions:
    - 7.0.0-alpha09
    - 7.0.0-alpha12
